name: "CI"
on:
  push:
    branches-ignore:
      - "release/**"
      - "docs"
    tags-ignore:
      - "**"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".travis.yml"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test Site
        run: bash tools/test.sh
